#! /usr/bin/perl -w
use strict;

my $current_label = "<<reset>>";
my $suppress_fall_through = 1;
my $last_was_skip = 0;

while (<>) {
  chop $_;
  s/;.*//;  # strip comments

  if (m/^\s*$/) { next }	# empty line
  if (m/^\.[a-z]+($| )/) { next }	# .equ or something alike

  if (m/^([A-Za-z_][A-Za-z0-9_]+):/) {
    # fished a jumpmark label
    unless ($suppress_fall_through) {
      print "\"$current_label\" -> \"$1\"; /* fall through */\n";
    }
    $current_label = $1;
  }

  if (m/(rjmp|rcall|br[a-z]{2})\s+([A-Za-z_][A-ZA-z0-9_]+)/) {
    print "\"$current_label\" -> \"$2\"; /* $1 */\n";
  }
  if (m/(rcall)\s+([A-Za-z_][A-ZA-z0-9_]+)/) {
    print "\"$2\" -> \"$current_label\"; /* $1 (reverse) */\n";
  }

  if ($last_was_skip == 0 && m/(rjmp|reti|ret)/) {
    $suppress_fall_through = 1;
  }
  else {
    $suppress_fall_through = 0;
  }

  if (m/\s+(sb.[cs])\s+/) {
    $last_was_skip = 1;
  }
  else {
    $last_was_skip = 0;
  }

}

